#+title: Doom Emacs Configuration
#+author: Mark Olson (mho)
#+startup: fold

* Introduction
* Issues
* Environment Setup
** Windows
*** Size
Proportionally resize the size of the window.
#+begin_src emacs-lisp
(setq-default window-combination-resize t)
#+end_src
Setting up the default frame size
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(height . 34))
(add-to-list 'default-frame-alist '(width  . 80))
#+end_src
*** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers appear. However, I prefer relative line numbers.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src
*** Scrolling
A little margin looks good.
#+begin_src emacs-lisp
(setq scroll-preserve-screen position 'always
      scroll-margin 4)
#+end_src
** Cursor
Stretch the width of the block cursor to match the width of the glyph.
#+begin_src emacs-lisp
(setq-default x-stretch-cursor t)
#+end_src
** Files
Sending deleted files to the trash and use auto-save ... just in case.
#+begin_src emacs-lisp
(setq-default delete-by-moving-to-trash t)
(setq auto-save-default t)
#+end_src
Raising the undo limit to 80Mb
#+begin_src emacs-lisp
(setq undo-limit 80000000)
#+end_src
** Fonts
Doom exposes five variables for controlling fonts.
*** Doom Primary Font
I rather like the SF Mono font.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "SF Mono" :size 21 ))
#+end_src
I also want to be able to insert SF Symbol fonts via
~completing-read~.

#+begin_src emacs-lisp
(set-fontset-font t nil "SF Pro Display" nil 'append)
(load! "lisp/sf.el")
#+end_src
*** Doom Variable Pitch Font
*** Doom Big Font
Let's Double the size for the Big Font.
#+begin_src emacs-lisp
(setq doom-big-font (font-spec :family "SF Mono" :size 42 ))
#+end_src
*** Doom Symbol Font
*** Doom Serif Font
** Keyboard
Since I am using using an Apple Swedish keyboard, it makes sence to define
the modifier keys such that:
- the option key can still be used to access commonly used symbols, and
- the meta and control keys are easily accessible with the thumbs.
#+begin_src emacs-lisp
(setq mac-option-modifier nil
      mac-command-modifier 'meta
      mac-right-command-modifier 'control
      mac-control-modifier 'super
      mac-function-modifier 'hyper)
#+end_src
** Themes
I really like working in dark-mode using the doom-nord-aurora theme.
#+begin_src emacs-lisp
(setq doom-theme 'doom-nord-aurora)
#+end_src
* Packages
** Convenience
*** Global Keybindings
** Tools
* Languages
** LaTeX
** Markdown
** Org
** Python
